name: AI
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 45

    steps:

    - name: IP1
      run: cmd /c nslookup myip.opendns.com resolver1.opendns.com
  
    - name: IP2 
      run: cmd /c curl ipinfo.io
